version: '3.9'

networks:
    transcendence:
        driver: bridge
services:
    django:
        build:
            context: ./src/app/django
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./src/app/django:/app/django
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - transcendence
    db:
        image: postgres:15.5-bullseye
        ports:
            - "5432:5432"
        volumes:
            - ./src/app/db:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
        networks:
            - transcendence