version: '3.9'

networks:
    transcendence:
        driver: bridge

services:
    front:
        build:
            context: ./src/app/front
            dockerfile: Dockerfile
        container_name: front
        ports:
            - "8080:8080"
        volumes:
            - ./src/app/front:/app/front
        depends_on:
            - nginx
        networks:
            - transcendence

    nginx:
        build:
            context: ./src/app/nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        ports:
            - "443:443"
            - "9113:9113"
        volumes:
            - ./src/app/front/dist:/usr/share/nginx/html
            - ./src/app/nginx:/app/nginx
        depends_on:
            - django
        networks:
            - transcendence

    django:
        build:
            context: ./src/app/django
            dockerfile: Dockerfile
        container_name: django
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./src/app/django:/app/django
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - transcendence

    db:
        image: postgres:15.5-bullseye
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./src/app/db:/var/lib/postgresql/data
            # - ./pg_config:/etc/postgresql
        environment:
            - SHARED_PRELOAD_LIBRARIES=pg_stat_statements,pg_prometheus
        env_file:
            - .env
        networks:
            - transcendence

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: always
        volumes:
            - ./src/app/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./src/app/prometheus/config/rules.yml:/etc/prometheus/rules.yml

        ports:
            - "9090:9090"
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        networks:
            - transcendence
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./src/app/grafana:/var/lib/grafana
        networks:
            - transcendence
    alertmanager:
        image: quay.io/prometheus/alertmanager
        container_name: alertmanager
        restart: always
        ports:
            - "9093:9093"
        volumes:
            - ./src/app/alertmanager:/etc/alertmanager
        networks:
            - transcendence
    discord-alerts:
        image: benjojo/alertmanager-discord
        container_name: discord-alerts
        restart: always
        environment:
            - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1228282712603754617/554undQORjiKu2u7zn6w07rdM5wDwbA5A6MfrEh1KGo6uj181CAgIaFTh7fS1aee_Kk3
        ports:
            - "9094:9094"
        networks:
            - transcendence
