version: '3.9'

networks:
    transcendence:
        driver: bridge
services:
    django:
        build:
            context: ./src/app/django
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./src/app/django:/app/django
        depends_on:
            - db
        networks:
            - transcendence
    db:
        image: postgres:13.3-alpine
        ports:
            - "5432:5432"
        volumes:
            - ./src/app/db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        networks:
            - transcendence
