global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['django:8000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    basic_auth:
      username: ${PROMETHEUS_USERNAME}
      password: ${PROMETHEUS_PASSWORD}
  
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # - job_name: 'postgres'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['postgres:5432']
  #   metric_relabel_configs:
  #     - source_labels: [__name__]
  #       regex: '.*_(connections|locks|transactions)_total' 
  #       action: keep
